/**
 * dsp_halfband.h — 2x polyphase half-band interpolator / decimator.
 *
 * Exists for one stage: the saturator is the only genuinely nonlinear thing in
 * the chain, so it is the only place oversampling buys anything (see
 * DEVELOPER_GUIDE.md §8, which reserves the latency for exactly this).
 *
 * The filter is a 31-tap equiripple half-band designed with Parks-McClellan,
 * bands [0, 17 kHz] and [31 kHz, 48 kHz] at the 96 kHz working rate — symmetric
 * about 24 kHz, which is what makes it half-band:
 *
 *   stopband        79.5 dB
 *   passband ripple 0.0018 dB
 *   20 kHz          -0.46 dB
 *
 * Half-band means every tap at an even offset from the centre is exactly zero
 * and the centre tap is exactly 0.5, so 31 taps cost 8 multiply-accumulates
 * (16 taps folded by symmetry) plus a copy. That structure is not an
 * optimisation detail — it is why one phase of each converter is a pure delay.
 *
 * Latency: 15 samples at the 2x rate per converter, so an up/down pair costs
 * exactly **15 samples at the base rate**. Individually each is 7.5 base-rate
 * samples, which is why only the pair is expressible as an integer delay — and
 * why anything that needs a matched dry path must delay by 15 and not by 7 or 8.
 *
 * The taps were generated by tools/halfband_design.py, whose output is asserted
 * against this table by sat_response_test's round-trip and stopband checks.
 */

#pragma once
#include <cstddef>

namespace mastering_dsp {

/** Taps at odd offsets +/-1, 3, 5, ..., 15 from the centre. Centre tap is 0.5
 *  and every even offset is zero, both implicit in the structure below. */
constexpr int   kHbPairs      = 8;
constexpr float kHbTap[kHbPairs] = {
     3.142954429708e-01f,   // offset +/-  1
    -9.457687605984e-02f,   // offset +/-  3
     4.604705175927e-02f,   // offset +/-  5
    -2.376020641321e-02f,   // offset +/-  7
     1.167728922778e-02f,   // offset +/-  9
    -5.113814964195e-03f,   // offset +/- 11
     1.839156183614e-03f,   // offset +/- 13
    -4.601692180459e-04f,   // offset +/- 15
};

/** Base-rate delay of an up/down pair. Anything running dry alongside the
 *  oversampled path must be delayed by this to stay sample-aligned. */
constexpr int kHbLatency = 15;

/** Power-of-two history so the wrap is a mask rather than a modulo. */
constexpr int kHbHist = 16;
constexpr int kHbMask = kHbHist - 1;

/**
 * Base rate -> 2x. One input sample yields two output samples.
 *
 * With the input zero-stuffed, output samples at odd 2x indices see only the
 * centre tap, so that phase is literally x[n-7]; the even phase carries all
 * eight folded taps. The factor of two restores the level the zero-stuffing
 * halved.
 */
struct HalfBandUp {
    void Process(float x, float& even, float& odd)
    {
        d_[w_] = x;
        float acc = 0.f;
        for (int i = 0; i < kHbPairs; ++i)
            acc += kHbTap[i] * (At(7 - i) + At(8 + i));
        even = 2.f * acc;
        odd  = At(7);
        w_   = (w_ + 1) & kHbMask;
    }

    void Reset() { for (int i = 0; i < kHbHist; ++i) d_[i] = 0.f; w_ = 0; }

  private:
    /** x[n - lag]; the newest sample was just written at w_. */
    float At(int lag) const { return d_[(w_ - lag) & kHbMask]; }

    float d_[kHbHist] = {};
    int   w_ = 0;
};

/**
 * 2x -> base rate. Consumes the two samples of one 2x frame, emits one.
 *
 * Split by phase, the centre tap lands entirely on the odd-phase history and
 * the folded taps entirely on the even-phase history — the mirror of the
 * interpolator, and the reason the pair's delay is an integer.
 */
struct HalfBandDown {
    float Process(float even, float odd)
    {
        ev_[w_] = even;
        od_[w_] = odd;
        float acc = 0.f;
        for (int i = 0; i < kHbPairs; ++i)
            acc += kHbTap[i] * (Ev(7 - i) + Ev(8 + i));
        const float y = acc + 0.5f * Od(8);
        w_ = (w_ + 1) & kHbMask;
        return y;
    }

    void Reset()
    {
        for (int i = 0; i < kHbHist; ++i) { ev_[i] = 0.f; od_[i] = 0.f; }
        w_ = 0;
    }

  private:
    float Ev(int lag) const { return ev_[(w_ - lag) & kHbMask]; }
    float Od(int lag) const { return od_[(w_ - lag) & kHbMask]; }

    float ev_[kHbHist] = {}, od_[kHbHist] = {};
    int   w_ = 0;
};

/** Plain base-rate delay for a dry path that must stay aligned with an
 *  oversampled wet path. Sized for kHbLatency, which is not a power of two. */
struct DryDelay {
    float Process(float x)
    {
        const float y = d_[w_];
        d_[w_] = x;
        w_ = (w_ + 1) % kHbLatency;
        return y;
    }

    void Reset() { for (int i = 0; i < kHbLatency; ++i) d_[i] = 0.f; w_ = 0; }

  private:
    float d_[kHbLatency] = {};
    int   w_ = 0;
};

} // namespace mastering_dsp
